table dCalendario
	lineageTag: 853449ff-1d06-4114-8f4c-b2014ce38594

	column Datas
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d8403a4-d223-4e32-a4d2-947042ab09c1
		summarizeBy: none
		sourceColumn: Datas

		variation Variation
			isDefault
			relationship: bc8a0203-6e69-408c-b78e-86448b1b9044
			defaultHierarchy: LocalDateTable_efbb9e7e-ee19-4ccb-967c-ad8556d2fcc7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: dcbb79bb-30b9-4f68-b03d-959f05470543
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: c16dd00a-89bf-4be6-a0c3-0e6014afbc6e
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 5988b1e1-a2a7-4718-bd91-812d8f938bc3
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 17803486-1fef-4fe7-b5ff-c6f7d8ad6fc0
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 3fcd31fd-5afb-4afb-b73f-61ce01cb0b23
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column 'Dia do Mês'
		dataType: int64
		formatString: 0
		lineageTag: f593ba25-b5f8-445b-9a13-dc8c7b9d0892
		summarizeBy: sum
		sourceColumn: Dia do Mês

		annotation SummarizationSetBy = Automatic

	column 'Mês Curto'
		dataType: string
		lineageTag: 957fe3cd-a225-4492-9592-fea9d70a3a23
		summarizeBy: none
		sourceColumn: Mês Curto

		annotation SummarizationSetBy = Automatic

	column 'Ano Mês'
		dataType: string
		lineageTag: e9c753e1-e168-4c67-a409-097c78e61e27
		summarizeBy: none
		sourceColumn: Ano Mês

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    DataMin = List.Min(orders[order_purchase_timestamp]),
				    DataMax = List.Max(orders[order_purchase_timestamp]),
				    QtdeDias = Duration.Days(DataMax - DataMin)+1,
				    Personalizar1 = List.Dates(Date.From(DataMin), QtdeDias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Datas"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Datas", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Datas]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Datas]), type text),
				    #"Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês", each Date.Month([Datas]), Int64.Type),
				    #"Trimestre Inserido" = Table.AddColumn(#"Mês Inserido", "Trimestre", each Date.QuarterOfYear([Datas]), Int64.Type),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Datas]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Dia do Mês", each Date.Day([Datas]), Int64.Type),
				    #"Nome do Mês Inserido1" = Table.AddColumn(#"Dia Inserido", "Mês Curto", each Text.Start(Date.MonthName([Datas]), 3), type text),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Nome do Mês Inserido1", "Ano Mês", each Text.Combine({Text.From([Ano], "pt-BR"), [Mês Curto]}, "/"), type text)
				in
				    #"Coluna Mesclada Inserida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

