table dCalendario
	lineageTag: 853449ff-1d06-4114-8f4c-b2014ce38594

	column Datas
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5d8403a4-d223-4e32-a4d2-947042ab09c1
		summarizeBy: none
		sourceColumn: Datas

		variation Variation
			isDefault
			relationship: bc8a0203-6e69-408c-b78e-86448b1b9044
			defaultHierarchy: LocalDateTable_efbb9e7e-ee19-4ccb-967c-ad8556d2fcc7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: dcbb79bb-30b9-4f68-b03d-959f05470543
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: c16dd00a-89bf-4be6-a0c3-0e6014afbc6e
		summarizeBy: none
		sourceColumn: Nome do Mês
		sortByColumn: 'Mês Número'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 17803486-1fef-4fe7-b5ff-c6f7d8ad6fc0
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: 3fcd31fd-5afb-4afb-b73f-61ce01cb0b23
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column 'Dia do Mês'
		dataType: int64
		formatString: 0
		lineageTag: f593ba25-b5f8-445b-9a13-dc8c7b9d0892
		summarizeBy: sum
		sourceColumn: Dia do Mês

		annotation SummarizationSetBy = Automatic

	column 'Mês Curto'
		dataType: string
		lineageTag: 957fe3cd-a225-4492-9592-fea9d70a3a23
		summarizeBy: none
		sourceColumn: Mês Curto
		sortByColumn: 'Mês Número'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AnoMês_Ordem
		dataType: int64
		formatString: 0
		lineageTag: 97984aae-7bd9-403c-aba9-327cbf064bee
		summarizeBy: sum
		sourceColumn: AnoMês_Ordem

		annotation SummarizationSetBy = Automatic

	column 'Mês Número'
		dataType: int64
		formatString: 0
		lineageTag: 1290434d-c39f-449f-97c0-607948852c15
		summarizeBy: sum
		sourceColumn: Mês Número

		annotation SummarizationSetBy = Automatic

	column 'Ano Mês'
		dataType: string
		lineageTag: eff8fdbd-5a0f-4e9d-bf37-80410b4c0555
		summarizeBy: none
		sourceColumn: Ano Mês
		sortByColumn: AnoMês_Ordem

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    // Faixa de datas
				    DataMin = Date.From(List.Min(orders[order_purchase_timestamp])),
				    DataMax = Date.From(List.Max(orders[order_purchase_timestamp])),
				    QtdeDias = Duration.Days(DataMax - DataMin) + 1,
				    ListaDatas = List.Dates(DataMin, QtdeDias, #duration(1,0,0,0)),
				
				    // Tabela de datas
				    #"Convertido para Tabela" = Table.FromList(ListaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela", {{"Column1","Datas"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas", {{"Datas", type date}}),
				
				    // Derivadas básicas
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Datas]), Int64.Type),
				    #"MesNumero Inserido" = Table.AddColumn(#"Ano Inserido", "Mês Número", each Date.Month([Datas]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"MesNumero Inserido", "Nome do Mês", each Date.ToText([Datas], "MMMM", "pt-BR"), type text),
				    #"Mês Curto Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês Curto", each Date.ToText([Datas], "MMM", "pt-BR"), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Mês Curto Inserido", "Trimestre", each Date.QuarterOfYear([Datas]), Int64.Type),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Datas]), Int64.Type),
				    #"Dia do Mês Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Dia do Mês", each Date.Day([Datas]), Int64.Type),
				
				    // Formatações finais
				    #"Ano Mês Inserido" = Table.AddColumn(
				        #"Dia do Mês Inserido",
				        "Ano Mês",
				        each Text.Proper([Mês Curto]) & "/" & Text.End(Text.From([Ano]), 2),
				        type text
				    ),
				    #"AnoMes_Ordem Inserido" = Table.AddColumn(
				        #"Ano Mês Inserido",
				        "AnoMês_Ordem",
				        each [Ano] * 100 + [Mês Número],
				        Int64.Type
				    )
				in
				    #"AnoMes_Ordem Inserido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

