table geolocation
	lineageTag: 6ac721b1-2c1f-4b77-8aef-a4440ea448c0

	column geolocation_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: b36cbca2-e9af-42d4-926e-148c38186758
		summarizeBy: none
		sourceColumn: geolocation_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column geolocation_city
		dataType: string
		lineageTag: 0d9a7761-5e55-4cc6-b086-08fd8aa97f76
		summarizeBy: none
		sourceColumn: geolocation_city

		annotation SummarizationSetBy = Automatic

	column geolocation_state
		dataType: string
		lineageTag: e5a9b0e5-e45a-4f3e-bd08-cb4b63bc2318
		summarizeBy: none
		sourceColumn: geolocation_state

		annotation SummarizationSetBy = Automatic

	partition geolocation = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\levia\Desktop\Profissional\data_challenge_olist_ecommerce\Turma 2 - Base de dados\geolocation.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"geolocation_zip_code_prefix", Int64.Type}, {"geolocation_lat", type number}, {"geolocation_lng", type number}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"geolocation_zip_code_prefix", "geolocation_city", "geolocation_state"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"geolocation_zip_code_prefix"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

