table lead_qualified
	lineageTag: bfd5c309-9e73-4f44-998c-be0866064ed4

	column mql_id
		dataType: string
		lineageTag: ab9579bf-471b-461b-907d-ebebd639f1a7
		summarizeBy: none
		sourceColumn: mql_id

		annotation SummarizationSetBy = Automatic

	column first_contact_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8471dbe4-d912-4fe2-ad8d-823c01830f3f
		summarizeBy: none
		sourceColumn: first_contact_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column landing_page_id
		dataType: string
		lineageTag: 6a838a27-bddc-4bb4-a67c-7da0a0abbb69
		summarizeBy: none
		sourceColumn: landing_page_id

		annotation SummarizationSetBy = Automatic

	column origin
		dataType: string
		lineageTag: 394bf0e8-a828-42dd-90b1-a7b095962539
		summarizeBy: none
		sourceColumn: origin

		annotation SummarizationSetBy = Automatic

	column closed? = COUNTROWS(FILTER(leads_closed, lead_qualified[mql_id] = leads_closed[mql_id]))
		formatString: 0
		lineageTag: 4a53273a-96ec-4d59-8908-0d063edaf71d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition lead_qualified = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\levia\Desktop\Profissional\data_challenge_olist_ecommerce\3. Base de Dados\lead_qualified.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"first_contact_date", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

