table Medidas
	lineageTag: 984a75ac-48db-4ca0-9198-8fc8f2400a4e

	measure faturamento = SUM(order_items[total_value])
		lineageTag: 87a1afea-7255-441c-a758-f5c67f5dc2a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure qtd_pedidos = COUNT(orders[order_id])
		formatString: 0
		lineageTag: c29721b9-0b1b-40a5-a828-cd7097153245

	measure qtd_entregues =
			
			CALCULATE(
			    [qtd_pedidos],
			    orders[order_status] = "delivered"
			)
		formatString: 0
		lineageTag: 51f67d41-5742-4254-85fd-1d471e931b32

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

