table Medidas
	lineageTag: 984a75ac-48db-4ca0-9198-8fc8f2400a4e

	measure 'Faturamento Total' = SUMX(order_items, order_items[price] + order_items[freight_value])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 1. Comercial
		lineageTag: 87a1afea-7255-441c-a758-f5c67f5dc2a5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Pedidos Realizados' = DISTINCTCOUNT(orders[order_id])
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: c29721b9-0b1b-40a5-a828-cd7097153245

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Pedidos Entregues' =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[order_id]),
			    orders[order_status] = "delivered"
			)
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 51f67d41-5742-4254-85fd-1d471e931b32

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Faturamento Produtos' = SUM(order_items[price])
		displayFolder: 1. Comercial
		lineageTag: fc8f13eb-a6fb-43c5-8c69-b6a60946ecd0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frete Total' = SUM(order_items[freight_value])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 1. Comercial
		lineageTag: fdc51476-32f5-496e-834e-089b1020b734

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Frete' = DIVIDE([Frete Total], [Faturamento Total])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Comercial
		lineageTag: dff55a3a-9e61-4963-b653-d6888e93ae8e

	measure 'Ticket Médio' = DIVIDE([Faturamento Total], [Pedidos Realizados])
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 1. Comercial
		lineageTag: b27bec55-7ca6-4a9f-9618-9480ac098738

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Pedidos no Prazo' =
			
			CALCULATE(
			    [Pedidos Entregues],
			    KEEPFILTERS(orders[order_delivered_customer_date] <= orders[order_estimated_delivery_date])
			)
		formatString: #,0
		displayFolder: 2. Logística
		lineageTag: 890ddbf8-c1ba-4992-82b0-f7a7d1e88dff

	measure 'Pedidos Atrasados' =
			
			CALCULATE(
			    [Pedidos Entregues],
			    KEEPFILTERS(orders[order_delivered_customer_date] > orders[order_estimated_delivery_date])
			)
		formatString: #,0
		displayFolder: 2. Logística
		lineageTag: 9bd63b68-8003-4c50-8935-ea4bd8704a5d

	measure 'OnTime Delivery' = DIVIDE([Pedidos no Prazo], [Pedidos Entregues])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 2. Logística
		lineageTag: d1df50c5-bdca-4fde-acd0-0c7efd4e5b73

	measure 'Lead Time (dias)' =
			
			AVERAGEX(
			    FILTER(orders, NOT ISBLANK(orders[order_delivered_customer_date])),
			    DATEDIFF(orders[order_approved_at_date], orders[order_delivered_customer_date], DAY)
			)
		displayFolder: 2. Logística
		lineageTag: b4be0acc-1ec8-455b-9fd3-404c906547c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nota Média' = AVERAGE(order_reviews[review_score])
		displayFolder: 3. Clientes e Satisfação
		lineageTag: 7abe6df1-0324-41ac-b4f4-747ced894c1e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nota Média — No Prazo' =
			
			CALCULATE([Nota Média],
			    KEEPFILTERS(orders[order_delivered_customer_date] <= orders[order_estimated_delivery_date])
			)
		displayFolder: 3. Clientes e Satisfação
		lineageTag: bfbd4285-a263-41b9-8f2c-79d11397af6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nota Média — Atrasado' =
			
			CALCULATE([Nota Média],
			    KEEPFILTERS(orders[order_delivered_customer_date] > orders[order_estimated_delivery_date])
			)
		displayFolder: 3. Clientes e Satisfação
		lineageTag: e5dfe102-aff3-4d17-9e9d-7f98829c69b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pedidos por Cliente' =
			
			VAR cliente = SELECTEDVALUE(customers[customer_unique_id])
			RETURN CALCULATE([Pedidos Realizados], ALLEXCEPT(customers, customers[customer_unique_id]))
		formatString: #,0
		displayFolder: 3. Clientes e Satisfação
		lineageTag: da80e6b0-a166-464b-8b4a-ca975c7e98b2

	measure 'Clientes Recorrentes' =
			
			COUNTROWS(FILTER(VALUES(customers[customer_unique_id]), [Pedidos por Cliente] >= 2))
		formatString: #,0
		displayFolder: 3. Clientes e Satisfação
		lineageTag: bcaa32ca-005c-45ac-9b66-8775c3b89838

	measure '% Clientes Recorrentes' = DIVIDE([Clientes Recorrentes], DISTINCTCOUNT(customers[customer_unique_id]))
		displayFolder: 3. Clientes e Satisfação
		lineageTag: 53827a5c-7332-4fb1-8e41-8f2cc1dfee2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clientes Únicos' = DISTINCTCOUNT(customers[customer_id])
		formatString: #,0
		displayFolder: 3. Clientes e Satisfação
		lineageTag: 29f43d24-688d-4319-b8bd-9f27084f9445

	measure 'Leads Qualificados' =
			
			DISTINCTCOUNT(lead_qualified[mql_id])
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 2e25302b-4b0d-40ee-952a-489592d442a4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Leads Fechados' =
			
			DISTINCTCOUNT(leads_closed[mql_id])
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 2db4241f-9c92-4af1-bf42-a804e55a7e4e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% Taxa Conversão Leads' =
			
			DIVIDE([Leads Fechados], [Leads Qualificados])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Comercial
		lineageTag: cad6f0e1-18b9-49be-a5ef-275f578a6f92

	measure 'Pedidos Realizados (Vend)' =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[order_id]),
			    CROSSFILTER(order_items[order_id], orders[order_id], BOTH)
			)
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: fe37cb07-b86f-4495-9db2-7b4df4891102

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Clientes Positivados' = CALCULATE(DISTINCTCOUNT(orders[customer_id]))
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 699df23e-58aa-4fcc-a1f2-7094d46b60ad

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Faturamento LY' =
			
			VAR AnoAtual = SELECTEDVALUE(dCalendario[Ano])
			RETURN
			CALCULATE(
			    [Faturamento Total],
			    FILTER(
			        ALL(dCalendario),                -- remove o filtro de 2018
			        dCalendario[Ano] = AnoAtual - 1  -- aplica o ano anterior
			    )
			)+0
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		displayFolder: 1. Comercial
		lineageTag: 8c22a828-de3c-46b0-810f-c4eaa1a3421d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Pedidos Realizados LY' =
			
			VAR AnoAtual = SELECTEDVALUE(dCalendario[Ano])
			RETURN
			CALCULATE(
			    [Pedidos Realizados],
			    FILTER(
			        ALL(dCalendario),                -- remove o filtro de 2018
			        dCalendario[Ano] = AnoAtual - 1  -- aplica o ano anterior
			    )
			)+0
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 0be76519-cb07-4ad2-999f-681b6ca3d1ee

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Faturamento YoY' =
			
			DIVIDE([Faturamento Total], [Faturamento LY]) - 1
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 1. Comercial
		lineageTag: 4ddfa0f8-ecd6-4dae-84f1-d8644900b4e7

	measure 'Faturamento YoY Texto' =
			
			FORMAT([Faturamento YoY], "↑ 0.0%; ↓ 0.0%")
		displayFolder: 1. Comercial
		lineageTag: f4f322d7-aa05-4d70-b00f-433f36d2006e

	measure 'Pedidos Realizados YoY' =
			
			DIVIDE([Pedidos Realizados], [Pedidos Realizados LY]) - 1
		displayFolder: 1. Comercial
		lineageTag: 41ce73da-34c6-4b69-917d-59a711a4f040

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pedidos Realizados YoY Texto' =
			
			FORMAT([Pedidos Realizados YoY], "↑ 0.0%; ↓ 0.0%")
		displayFolder: 1. Comercial
		lineageTag: 6af90079-da01-4f1f-bb24-eee9ee18b09b

	measure 'Pedidos Entregues LY' =
			
			VAR AnoAtual = SELECTEDVALUE(dCalendario[Ano])
			RETURN
			CALCULATE(
			    [Pedidos Entregues],
			    FILTER(
			        ALL(dCalendario),                -- remove o filtro de 2018
			        dCalendario[Ano] = AnoAtual - 1  -- aplica o ano anterior
			    )
			)+0
		formatString: #,0
		displayFolder: 1. Comercial
		lineageTag: 82c32873-f6a7-4df2-b9bd-035741927546

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Pedidos Entregues YoY' =
			
			DIVIDE([Pedidos Entregues], [Pedidos Entregues LY]) - 1
		displayFolder: 1. Comercial
		lineageTag: e8c74585-a415-422c-8790-7b3f37aa7859

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pedidos Entregues YoY Texto' =
			
			FORMAT([Pedidos Entregues YoY], "↑ 0.0%; ↓ 0.0%")
		displayFolder: 1. Comercial
		lineageTag: fd88fc37-025f-49dc-9229-4e7050477afd

	measure 'Ticket Médio LY' =
			
			VAR AnoAtual = SELECTEDVALUE(dCalendario[Ano])
			RETURN
			CALCULATE(
			    [Ticket Médio],
			    FILTER(
			        ALL(dCalendario),                -- remove o filtro de 2018
			        dCalendario[Ano] = AnoAtual - 1  -- aplica o ano anterior
			    )
			)+0
		displayFolder: 1. Comercial
		lineageTag: bc06fccf-1973-4426-b51a-a05a8ab534bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ticket Médio YoY' =
			
			DIVIDE([Ticket Médio], [Ticket Médio LY]) - 1
		displayFolder: 1. Comercial
		lineageTag: 00e776b2-9ed2-4d23-a722-8b575dcaebbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ticket Médio YoY Texto' =
			
			FORMAT([Ticket Médio YoY], "↑ 0.0%; ↓ 0.0%")
		displayFolder: 1. Comercial
		lineageTag: af04246c-b9da-47ad-a760-9d49305b9b99

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

