table order_items
	lineageTag: 5c3ede55-5b06-4a7e-a873-b186f3f66546

	column order_id
		dataType: string
		lineageTag: ddb631ec-4b4d-4b8d-af6d-591747a83f59
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: bb1d1b74-0415-4d81-b8a7-d2f34faa857d
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 71571934-d090-4368-9b57-4b10b732d904
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: 09711b64-f4a6-42bd-aeb1-c7adf4591443
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 34f7f437-1dc2-40bd-8b73-fb784ffd02f1
		summarizeBy: none
		sourceColumn: shipping_limit_date

		variation Variation
			isDefault
			relationship: b01f08c2-ac1d-4a45-86a9-3a240356d79b
			defaultHierarchy: LocalDateTable_442fdf23-c2be-4168-8694-72c6a665f003.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: 72eecba7-4b0e-43d6-b12d-38cc41da9a50
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value
		dataType: double
		lineageTag: 35951871-0b8d-4e0a-a5f2-ab2e187aa274
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_value = order_items[price] + order_items[freight_value]
		lineageTag: f050d8f9-4fe9-4574-bdfd-3a04d5ee356f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition order_items = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\levia\Desktop\Profissional\data_challenge_olist_ecommerce\3. Base de Dados\order_items.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"order_item_id", Int64.Type}, {"shipping_limit_date", type datetime}, {"price", type number}, {"freight_value", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

