table order_reviews
	lineageTag: 316a026a-003c-48c1-9711-d919884c5c0c

	column review_id
		dataType: string
		lineageTag: 486c2c97-3879-4257-be89-db8f87983786
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 5ce66ba7-50f0-44fc-a4e5-e6620133de79
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 30a1d9c6-c0f9-4c72-83bf-a6caa9a12ab8
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column review_comment_title
		dataType: string
		lineageTag: 3a86f58b-e2fd-4f89-ade6-add2e6fa503b
		summarizeBy: none
		sourceColumn: review_comment_title

		annotation SummarizationSetBy = Automatic

	column review_comment_message
		dataType: string
		lineageTag: e8030b6c-4a52-40e2-ad83-8c8c423056d4
		summarizeBy: none
		sourceColumn: review_comment_message

		annotation SummarizationSetBy = Automatic

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 04dd77bd-3b68-451d-9318-0068aa3a8630
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: 4a1491a9-3a09-4d57-826c-0e43b30b2e22
			defaultHierarchy: LocalDateTable_76f1c771-1516-4124-b36a-219a8dee0f1c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column review_answer_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 6e175004-4e98-42ab-a0d0-e30773774d49
		summarizeBy: none
		sourceColumn: review_answer_timestamp

		variation Variation
			isDefault
			relationship: 998c16d3-4e74-49e2-b0de-ca3751b12c66
			defaultHierarchy: LocalDateTable_2f930451-47be-4813-bb38-2e8929510509.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition order_reviews = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\levia\Desktop\Profissional\data_challenge_olist_ecommerce\3. Base de Dados\order_reviews.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"review_score", Int64.Type}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

