table sellers
	lineageTag: a7b9434a-e12c-4eab-8bba-43ebdbfb6429

	column seller_id
		dataType: string
		lineageTag: 4ec5ef6a-7723-4db8-bb2e-367fccde1dff
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 8b8cbe02-6e01-47f6-a404-c8a4f1bbde1e
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: 83d56909-e62c-431c-98bb-1171a27101a2
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 00fb472c-5372-4d9b-a54e-1785ae255dae
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	partition sellers = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\levia\Desktop\Profissional\data_challenge_olist_ecommerce\3. Base de Dados\sellers.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"seller_zip_code_prefix", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

